// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;

public type Order record {
    string id;
    "new"|"shipped"|"delivered" status;
    decimal shippingFee?;
    decimal total;
    string shippingAddress?;
    string createdAt;
    OrderItem[] items;
};

public type Product record {
    string id;
    string name;
    string description?;
    decimal price;
    string imageUrl?;
    "available"|"sold" status;
};

public type Error record {
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
};

public type CartItem record {
    string productId;
    string name;
    decimal price;
};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};

public type orders_orderId_body record {
    "new"|"shipped"|"delivered" status;
};

public type ProductInput record {
    string name;
    string description?;
    decimal price;
    string imageUrl?;
};

public type ErrorNotFound record {|
    *http:NotFound;
    Error body;
|};

public type OrderInput record {
    string cartId;
    string shippingAddress;
    # tokenized payment detail from the payment provider
    string paymentToken;
};

public type cartId_items_body record {
    string productId;
};

public type OrderItem record {
    string productId;
    string name;
    decimal price;
};

public type inline_response_200_1 record {
    # total matching items
    int count;
    # relative URI of the next page
    string? next?;
    # relative URI of the previous page
    string? previous?;
    Order[] data;
};

public type inline_response_200 record {
    # total matching items
    int count;
    # relative URI of the next page
    string? next?;
    # relative URI of the previous page
    string? previous?;
    Product[] data;
};

public type ErrorForbidden record {|
    *http:Forbidden;
    Error body;
|};

public type CartOk record {|
    *http:Ok;
    Cart body;
|};

public type ErrorUnauthorized record {|
    *http:Unauthorized;
    Error body;
|};

public type Cart record {
    string id;
    CartItem[] items;
};
